### ISSUE TITLE
heroku local npm ERR! code EJSONPARSE

### ISSUE THREAD

**Issue by Operationbackfire** [Operationbackfire/loc8r#1]
I have tried to run the command
 heroku local web
I follow the tutorial in the book Getting MEAN with... so its an Express app I am making. 
I have tried to run 
 npm cache clean
and it didn't work.

Procfile
------------
web: npm start
-------

screen output
---------------
[OKAY] Loaded ENV .env File as KEY=VALUE Format
10.27.43 web.1   |  npm
10.27.43 web.1   |   ERR! file /Users/*******/100daysofcode/expressapp/loc8r/package.json
10.27.43 web.1   |  npm ERR! code EJSONPARSE
10.27.43 web.1   |  npm ERR! Failed to parse json
10.27.43 web.1   |  npm ERR! Unexpected string in JSON at position 175 while parsing '{
10.27.43 web.1   |  npm ERR!   "name": "loc8r",
10.27.43 web.1   |  npm ERR!   "version": "0.0.0'
10.27.43 web.1   |  npm ERR! File: /Users/*********/100daysofcode/expressapp/loc8r/package.json
10.27.43 web.1   |  npm ERR! Failed to parse package.json data.
10.27.43 web.1   |  npm ERR! package.json must be actual JSON, not just JavaScript.
10.27.43 web.1   |  npm ERR! 
10.27.43 web.1   |  npm ERR! Tell the package author to fix their package.json file. JSON.parse
10.27.43 web.1   |  npm ERR! A complete log of this run can be found in:
10.27.43 web.1   |  npm ERR!     /Users/*********/.npm/_logs/2018-01-20T09_27_43_974Z-debug.log
-----------------

log-file
-----------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose stack Error: Failed to parse json
4 verbose stack Unexpected string in JSON at position 175 while parsing '{
4 verbose stack   "name": "loc8r",
4 verbose stack   "version": "0.0.0'
4 verbose stack     at parseError (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:11)
4 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:104:26)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:51:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
5 verbose cwd /Users/*************/100daysofcode/expressapp/loc8r
6 verbose Darwin 17.3.0
7 verbose argv "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/bin/npm" "start"
8 verbose node v9.4.0
9 verbose npm  v5.6.0
10 error file /Users/*************/100daysofcode/expressapp/loc8r/package.json
11 error code EJSONPARSE
12 error Failed to parse json
12 error Unexpected string in JSON at position 175 while parsing '{
12 error   "name": "loc8r",
12 error   "version": "0.0.0'
13 error File: /Users/**********/100daysofcode/expressapp/loc8r/package.json
14 error Failed to parse package.json data.
14 error package.json must be actual JSON, not just JavaScript.
14 error
14 error Tell the package author to fix their package.json file. JSON.parse
15 verbose exit [ 1, true ]
-----------------------------------------------

**Comment by Operationbackfire** [comment]
solved by comment in
https://stackoverflow.com/questions/43215789/npm-err-code-ejsonparse-failed-to-parse-json

Not sure why you did all that when the error is pretty clear: the JSON in package.json contains a syntax error on line 26. Try running it through a validator like this one. – robertklep Apr 4 '17 at 19:24
